# Generated by Django 4.2.7 on 2023-12-01 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqoption_permitir', models.BooleanField(default=False, verbose_name=' Permitir Operações Trader')),
                ('iqoption_email', models.CharField(blank=True, max_length=100, verbose_name='E-mail')),
                ('iqoption_password', models.CharField(blank=True, max_length=100, verbose_name='Senha')),
                ('iqoption_type', models.CharField(choices=[('REAL', 'Real'), ('PRACTICE', 'Treinamento')], default='PRACTICE', max_length=10, verbose_name='Tipo de Conta')),
                ('iqoption_real_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Conta Real')),
                ('iqoption_real_saldo_display', models.CharField(default='0,00', max_length=20, verbose_name='Saldo Conta Real')),
                ('iqoption_practice_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Conta Treinamento')),
                ('iqoption_practice_saldo_display', models.CharField(default='0,00', max_length=20, verbose_name='Saldo Conta Treinamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
