# Generated by Django 4.2.7 on 2023-11-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iqoption',
            field=models.BooleanField(default=False, verbose_name='IQ Option'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iqoption_email',
            field=models.CharField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iqoption_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='Celular'),
        ),
    ]
