# Generated by Django 4.2.7 on 2023-11-29 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_userprofile_cpf_alter_userprofile_iqoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iqoption', models.BooleanField(default=False, verbose_name='IQ Option')),
                ('iqoption_email', models.CharField(blank=True, max_length=100, verbose_name='E-mail')),
                ('iqoption_password', models.CharField(blank=True, max_length=100, verbose_name='Senha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
