# Generated by Django 4.2.7 on 2023-11-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_iqoption_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqoption',
            name='iqoption',
            field=models.BooleanField(default=False, verbose_name=' Permitir Operações Trader'),
        ),
    ]
