# Generated by Django 4.2.7 on 2023-11-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_iqoption_iqoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqoption',
            old_name='iqoption',
            new_name='iqoption_permitir',
        ),
    ]
