# Generated by Django 4.2.7 on 2023-11-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_iqoption_iqoption_iqoption_permitir'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('PRACTICE', 'Treinamento'), ('TOURNAMENT', 'Torneio')], default='REAL', max_length=10),
        ),
    ]
