# Generated by Django 4.2.7 on 2023-11-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_iqoption_iqoption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_practice_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Treinamento'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_real_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Real'),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_tournament_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Torneio'),
        ),
        migrations.AlterField(
            model_name='iqoption',
            name='iqoption_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('PRACTICE', 'Treinamento'), ('TOURNAMENT', 'Torneio')], default='PRACTICE', max_length=10, verbose_name='Tipo de Conta'),
        ),
    ]
