# Generated by Django 4.2.7 on 2023-11-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_iqoption_iqoption_practice_saldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iqoption',
            name='iqoption_tournament_saldo',
        ),
        migrations.AlterField(
            model_name='iqoption',
            name='iqoption_practice_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Conta Treinamento'),
        ),
        migrations.AlterField(
            model_name='iqoption',
            name='iqoption_real_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Conta Real'),
        ),
        migrations.AlterField(
            model_name='iqoption',
            name='iqoption_type',
            field=models.CharField(choices=[('REAL', 'Real'), ('PRACTICE', 'Treinamento')], default='PRACTICE', max_length=10, verbose_name='Tipo de Conta'),
        ),
    ]
