# Generated by Django 4.2.7 on 2023-11-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_iqoption_iqoption_tournament_saldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_practice_saldo_display',
            field=models.CharField(default='0,00', max_length=20),
        ),
        migrations.AddField(
            model_name='iqoption',
            name='iqoption_real_saldo_display',
            field=models.CharField(default='0,00', max_length=20),
        ),
    ]
