"""
Django settings for MercadoFinanceiro project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uh=eu6p#9m%%$^bgtehd0(ooi!ruo_ry$flfnexh_q$iw(!4!6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Aplicações do Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplicações de terceiros
    'django_crontab',

    # Aplicações
    'accounts',
    'iqoption',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MercadoFinanceiro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MercadoFinanceiro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mercadofinanceiro',
        'USER': 'weth',
        'PASSWORD': 'weth1q2w3e4r',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações do Django Crontab (Exrcutar tarefas agendadas)
# https://pypi.org/project/django-crontab/

CRONJOBS = [
    ('0,5,10,15,20,25,30,35,40,45,50,55 * * * *', 'iqoption.cron.cron_atualizar_ativos_binarios'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audcad'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audcadotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audchf'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audnzd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_audusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_btcusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_cadchf'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_cadjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_chfjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eosusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_ethusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_euraud'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurcad'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurchf'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurgbp'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurgbpotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurjpyotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurnzd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_eurusdotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpaud'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpcad'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpchf'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpjpyotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpnzd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_gbpusdotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_ltcusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_nzdusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_nzdusdotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdbrl'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdcad'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdchf'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdchfotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdhkd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdhkdotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdinr'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdinrotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdjpy'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdjpyotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdnok'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdpln'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdrub'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdsek'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdsgd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdsgdotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdtry'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdzar'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usdzarotc'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_usousd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_xauusd'),
    ('* * * * *', 'iqoption.cron.cron_atualizar_candles_xrpusd'),
]
