# Generated by Django 4.2.7 on 2023-12-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosBinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_binario', models.CharField(max_length=20, verbose_name='Ativos Binários')),
                ('ativo_binario_aberto', models.BooleanField(default=False, verbose_name='Aberto')),
                ('ativo_binario_m1', models.BooleanField(default=False, verbose_name='M1')),
                ('ativo_binario_m1_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro M1')),
                ('ativo_binario_m5', models.BooleanField(default=False, verbose_name='M5')),
                ('ativo_binario_m5_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro M5')),
            ],
        ),
    ]
