# Generated by Django 4.2.7 on 2023-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosBinarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo_binario', models.CharField(choices=[('AUDCAD', 'AUD/CAD'), ('AUDJPY', 'AUD/JPY'), ('AUDUSD', 'AUD/USD'), ('CADCHF', 'CAD/CHF'), ('EURGBP', 'EUR/GBP'), ('EURJPY', 'EUR/JPY'), ('EURUSD', 'EUR/USD'), ('GBPJPY', 'GBP/JPY'), ('GBPUSD', 'GBP/USD'), ('USDJPY', 'USD/JPY'), ('USDCAD', 'USD/CAD'), ('USDCHF', 'USD/CHF'), ('XAUUSD', 'OURO'), ('AUDCAD-OTC', 'AUD/CAD (OTC)'), ('EURGBP-OTC', 'EUR/GBP (OTC)'), ('EURJPY-OTC', 'EUR/JPY (OTC)'), ('EURUSD-OTC', 'EUR/USD (OTC)'), ('GBPJPY-OTC', 'GBP/JPY (OTC)'), ('GBPUSD-OTC', 'GBP/USD (OTC)'), ('NZDUSD-OTC', 'NZD/USD (OTC)'), ('USDCHF-OTC', 'USD/CHF (OTC)'), ('USDJPY-OTC', 'USD/JPY (OTC)')], max_length=20, verbose_name='Ativi Binário')),
                ('ativo_binario_aberto', models.BooleanField(default=False, verbose_name='Aberto')),
                ('ativo_binario_m1', models.BooleanField(default=False, verbose_name='M1')),
                ('ativo_binario_m1_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro M1')),
                ('ativo_binario_m5', models.BooleanField(default=False, verbose_name='M5')),
                ('ativo_binario_m5_lucro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro M5')),
            ],
        ),
    ]
