# Generated by Django 4.2.7 on 2023-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqoption', '0003_alter_ativosbinarios_ativo_binario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosbinarios',
            name='ativo_binario_m1_lucro_display',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro M1'),
        ),
        migrations.AddField(
            model_name='ativosbinarios',
            name='ativo_binario_m5_lucro_display',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro M5'),
        ),
    ]
