# Generated by Django 4.2.7 on 2023-12-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqoption', '0006_alter_ativosbinarios_ativo_binario_m1_lucro_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativosbinarios',
            name='ativo_binario_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualização'),
        ),
    ]
